package main

import (
	"context"
	_ "embed"
	"encoding/json"
	"fmt"
	"log/slog"

	"github.com/opentalon/opentalon/pkg/plugin"
	"github.com/opentalon/talon-language/pkg/talon"
)

//go:embed workflow_tool.txt
var workflowToolDoc string

// config is the JSON shape this plugin accepts from the host's
// `plugins.<name>.config:` block. All fields are optional.
type config struct {
	// DatalevinURL points at a Datalevin HTTP server. When set, the
	// plugin uses talon.Run (full language: workflow + detect + queries
	// + ML primitives). When empty, only workflow-only programs run
	// via talon.RunWorkflow — detect-bearing programs return
	// ErrRequiresFactStore from the SDK.
	DatalevinURL string `json:"datalevin_url"`
}

// handler implements pkg/plugin.StreamingHandler. The plugin advertises
// SupportsCallbacks=true so the host dispatches over the bidirectional
// ExecuteBidi stream and passes a live HostCaller — that's how every
// MCP step inside a Talon program flows back through the host's
// expert system (executeCall → policy → observability → credentials).
type handler struct {
	cfg config
}

// Configure parses the host-supplied config block. Empty configJSON is
// valid — the plugin runs in workflow-only mode.
func (h *handler) Configure(configJSON string) error {
	if configJSON == "" {
		return nil
	}
	if err := json.Unmarshal([]byte(configJSON), &h.cfg); err != nil {
		return fmt.Errorf("talon-plugin: parse config: %w", err)
	}
	if h.cfg.DatalevinURL != "" {
		slog.Info("talon-plugin: datalevin backend configured", "url", h.cfg.DatalevinURL)
	} else {
		slog.Info("talon-plugin: workflow-only mode (no datalevin_url configured)")
	}
	return nil
}

func (h *handler) Capabilities() plugin.CapabilitiesMsg {
	return plugin.CapabilitiesMsg{
		Name:        "talon-plugin",
		Description: "Executes Talon workflow blocks — deterministic multi-step MCP chains generated by the LLM for batch operations.",
		Actions: []plugin.ActionMsg{
			{
				Name:        "execute_workflow",
				Description: "Execute a Talon workflow block as a single atomic operation. See system_prompt_addition for the DSL syntax and examples.",
				Parameters: []plugin.ParameterMsg{
					{
						Name:        "workflow",
						Description: "Talon workflow source: a single `workflow \"...\" { step \"...\" { mcp \"<server>\" \"<tool>\" { ... } } }` block.",
						Type:        "string",
						Required:    true,
					},
				},
			},
		},
		SystemPromptAddition: workflowToolDoc,
		SupportsCallbacks:    true,
	}
}

// Execute is the unary path — never called by the host for this plugin
// because we declare SupportsCallbacks=true above. Implemented so the
// type satisfies plugin.Handler, but returns a clear error so a
// misconfigured host (e.g. older opentalon without bidi support)
// surfaces the mismatch loudly instead of silently mis-running.
func (h *handler) Execute(req plugin.Request) plugin.Response {
	return plugin.Response{
		CallID: req.ID,
		Error:  "talon-plugin requires the host to dispatch over ExecuteBidi (host opentalon >= v0.0.18). The unary path is not supported.",
	}
}

// ExecuteWithCallbacks is the bidi path. It receives a live HostCaller
// the talon runtime uses to dispatch each `mcp "<server>" "<tool>"`
// step back through the host's orchestrator.
func (h *handler) ExecuteWithCallbacks(ctx context.Context, req plugin.Request, host plugin.HostCaller) plugin.Response {
	if req.Action != "execute_workflow" {
		return plugin.Response{CallID: req.ID, Error: "unknown action: " + req.Action}
	}
	src := req.Args["workflow"]
	if src == "" {
		return plugin.Response{CallID: req.ID, Error: "workflow argument is required; pass a Talon workflow block as a string"}
	}

	slog.Info("talon-plugin: execute_workflow",
		"call_id", req.ID,
		"workflow_len", len(src),
		"datalevin", h.cfg.DatalevinURL != "")

	result, err := h.runTalon(ctx, src, req.ID, host)
	if err != nil {
		return plugin.Response{
			CallID: req.ID,
			Error:  fmt.Sprintf("talon-plugin: %v", err),
		}
	}

	content, structured := formatResult(result)
	return plugin.Response{
		CallID:            req.ID,
		Content:           content,
		StructuredContent: structured,
	}
}

// runTalon picks the right SDK entry point based on whether a Datalevin
// backend is configured. With one, talon.Run handles the full language
// (workflows + detect + queries + ML primitives). Without one we fall
// back to talon.RunWorkflow which is faster but rejects detect-bearing
// programs with talon.ErrRequiresFactStore — the LLM gets a clear error
// pointing at the missing config rather than a panic.
func (h *handler) runTalon(ctx context.Context, src, callID string, host plugin.HostCaller) (*talon.Result, error) {
	opts := []talon.Option{
		talon.WithMCP(&talonCaller{host: host}),
		talon.WithFilename("workflow:" + callID),
	}
	if h.cfg.DatalevinURL != "" {
		opts = append(opts, talon.WithDatalevinURL(h.cfg.DatalevinURL))
		return talon.Run(ctx, src, opts...)
	}
	return talon.RunWorkflow(ctx, src, opts...)
}

// talonCaller bridges talon-language's MCPCaller interface (args
// map[string]any → any) to the host SDK's HostCaller (args
// map[string]string → CallResult). Each side carries the data the
// other doesn't natively understand, so we JSON-encode the args on
// the way out and parse the reply on the way back.
type talonCaller struct {
	host plugin.HostCaller
}

func (c *talonCaller) Call(ctx context.Context, server, tool string, args map[string]any) (any, error) {
	// Args cross the gRPC boundary as map[string]string per the
	// existing tool-call contract. The host re-parses them when
	// delivering to the target plugin; for talon arguments that are
	// non-strings (numbers, bools, nested maps) we JSON-encode the
	// whole arg value so the receiver can decode back if needed.
	encoded := make(map[string]string, len(args))
	for k, v := range args {
		if s, ok := v.(string); ok {
			encoded[k] = s
			continue
		}
		b, err := json.Marshal(v)
		if err != nil {
			return nil, fmt.Errorf("encode arg %q: %w", k, err)
		}
		encoded[k] = string(b)
	}

	res, err := c.host.RunAction(ctx, server, tool, encoded)
	if err != nil {
		return nil, err
	}

	// Prefer structured content when the upstream tool produced it
	// (that's the schema-validated JSON record per MCP 2025-06). Fall
	// back to the human-readable content string and try to JSON-decode
	// it so workflow expressions like step("find").result.items work.
	payload := res.StructuredContent
	if payload == "" {
		payload = res.Content
	}
	if payload == "" {
		return map[string]any{}, nil
	}

	var parsed any
	if err := json.Unmarshal([]byte(payload), &parsed); err == nil {
		return parsed, nil
	}
	return map[string]any{"text": payload}, nil
}

// formatResult renders a workflow run as a human-readable summary
// (Content) and a JSON payload (StructuredContent) carrying the
// per-step trace. The summary is what the LLM sees; the structured
// blob is for clients that want the raw step-by-step view.
func formatResult(r *talon.Result) (string, string) {
	type stepEntry struct {
		Type   string `json:"type"`
		Name   string `json:"name"`
		Output any    `json:"output,omitempty"`
	}
	type blockEntry struct {
		Steps []stepEntry `json:"steps"`
	}

	blocks := map[string]blockEntry{}
	totalSteps := 0
	for name, b := range r.Blocks {
		be := blockEntry{}
		for _, s := range b.Steps {
			be.Steps = append(be.Steps, stepEntry{Type: s.Type, Name: s.Name, Output: s.Output})
			totalSteps++
		}
		blocks[name] = be
	}
	summary := fmt.Sprintf("Workflow completed: %d block(s), %d step(s).", len(blocks), totalSteps)
	if totalSteps == 0 {
		summary = "Workflow executed (no steps)."
	}

	out, err := json.Marshal(map[string]any{"blocks": blocks})
	if err != nil {
		return summary, ""
	}
	return summary, string(out)
}
